package jbreakout.view;

public class GameOverWindow extends javax.swing.JFrame {
	
	private static GameOverWindow instance = null;

    /**
     * Creates new form GameOverWindow
     */
    public GameOverWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        gameOverLabel = new javax.swing.JLabel();
        setNameLabel(new javax.swing.JLabel());
        setScoreLabel(new javax.swing.JLabel());
        mainMenuButton = new javax.swing.JButton();
        quitButton = new javax.swing.JButton();
        setScoreMessageLabel(new javax.swing.JLabel());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        gameOverLabel.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        gameOverLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gameOverLabel.setText("GAME OVER");

        getNameLabel().setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getNameLabel().setText("Name: <name>");

        getScoreLabel().setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getScoreLabel().setText("Score: <score>");

        mainMenuButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mainMenuButton.setText("Main menu");
        mainMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMenuButtonActionPerformed(evt);
            }
        });

        quitButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        quitButton.setText("Quit");
        quitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitButtonActionPerformed(evt);
            }
        });

        getScoreMessageLabel().setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getScoreMessageLabel().setText("Your score was/was not registered on the Hall of Fame.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gameOverLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mainMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(quitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(getNameLabel(), javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(getScoreLabel(), javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(getScoreMessageLabel(), javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gameOverLabel)
                .addGap(46, 46, 46)
                .addComponent(getNameLabel())
                .addGap(27, 27, 27)
                .addComponent(getScoreLabel())
                .addGap(34, 34, 34)
                .addComponent(getScoreMessageLabel())
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mainMenuButton)
                    .addComponent(quitButton))
                .addContainerGap())
        );
        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void mainMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {                                               
    	MainWindow.getInstance();
        MainWindow.getInstance().setVisible(true);
        dispose();
    }                                              

    private void quitButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
        dispose();
    }                                           

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameOverWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameOverWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameOverWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameOverWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameOverWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel gameOverLabel;
    private javax.swing.JButton mainMenuButton;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JButton quitButton;
    private javax.swing.JLabel scoreLabel;
    private javax.swing.JLabel scoreMessageLabel;
    // End of variables declaration              
    
    public static GameOverWindow getInstance() {
		if (instance == null) {
			instance = new GameOverWindow();
		}
		return instance;
	}
    
    public javax.swing.JLabel getGameOverLabel() {
    	return gameOverLabel;
    }

	public javax.swing.JLabel getNameLabel() {
		return nameLabel;
	}

	public void setNameLabel(javax.swing.JLabel nameLabel) {
		this.nameLabel = nameLabel;
	}

	public javax.swing.JLabel getScoreLabel() {
		return scoreLabel;
	}

	public void setScoreLabel(javax.swing.JLabel scoreLabel) {
		this.scoreLabel = scoreLabel;
	}

	public javax.swing.JLabel getScoreMessageLabel() {
		return scoreMessageLabel;
	}

	public void setScoreMessageLabel(javax.swing.JLabel scoreMessageLabel) {
		this.scoreMessageLabel = scoreMessageLabel;
	}
    
}

