package jbreakout.view;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

import javax.swing.JLabel;

import jbreakout.controller.ControllerForView;

public class SavedGamesWindow extends javax.swing.JFrame {
	
	private static SavedGamesWindow instance = null;
	
	public static final int SAVE_SLOTS_NUMBER = 5;

    /**
     * Creates new form SavedGamesWindow
     */
    private SavedGamesWindow() {
        initComponents();
        setLocationRelativeTo(null);
        addWindowListener(new WindowAdapter() {
        	public void windowClosing(WindowEvent evt) {
        		onExit();
    	    }
    	});
    }
    private void onExit() {
    	this.setVisible(false);
    	ControllerForView.getInstance().openStartWindow();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        savedGamesTitleLabel = new javax.swing.JLabel();
        savedGameLabel1 = new javax.swing.JLabel();
        savedGameLabel2 = new javax.swing.JLabel();
        loadButton2 = new javax.swing.JButton();
        clearButton2 = new javax.swing.JButton();
        savedGameLabel3 = new javax.swing.JLabel();
        loadButton3 = new javax.swing.JButton();
        clearButton3 = new javax.swing.JButton();
        savedGameLabel4 = new javax.swing.JLabel();
        loadButton4 = new javax.swing.JButton();
        clearButton4 = new javax.swing.JButton();
        loadButton5 = new javax.swing.JButton();
        savedGameLabel5 = new javax.swing.JLabel();
        clearButton5 = new javax.swing.JButton();
        loadButton1 = new javax.swing.JButton();
        clearButton1 = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton2.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        savedGamesTitleLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        savedGamesTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        savedGamesTitleLabel.setText("Saved Games:");

        savedGameLabel1.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        savedGameLabel1.setText("Player: Riccardo; Score: 300");

        savedGameLabel2.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        savedGameLabel2.setText("Player: Riccardo; Score: 300");

        loadButton2.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        loadButton2.setText("Load");
        loadButton2.setMargin(new java.awt.Insets(2, 10, 2, 10));
        loadButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadButton2ActionPerformed(evt);
            }
        });

        clearButton2.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        clearButton2.setText("Clear");
        clearButton2.setMargin(new java.awt.Insets(2, 10, 2, 10));
        clearButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButton2ActionPerformed(evt);
            }
        });

        savedGameLabel3.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        savedGameLabel3.setText("Player: Riccardo; Score: 300");

        loadButton3.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        loadButton3.setText("Load");
        loadButton3.setMargin(new java.awt.Insets(2, 10, 2, 10));
        loadButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadButton3ActionPerformed(evt);
            }
        });

        clearButton3.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        clearButton3.setText("Clear");
        clearButton3.setMargin(new java.awt.Insets(2, 10, 2, 10));
        clearButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButton3ActionPerformed(evt);
            }
        });

        savedGameLabel4.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        savedGameLabel4.setText("Player: Riccardo; Score: 300");

        loadButton4.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        loadButton4.setText("Load");
        loadButton4.setMargin(new java.awt.Insets(2, 10, 2, 10));
        loadButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadButton4ActionPerformed(evt);
            }
        });

        clearButton4.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        clearButton4.setText("Clear");
        clearButton4.setMargin(new java.awt.Insets(2, 10, 2, 10));
        clearButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButton4ActionPerformed(evt);
            }
        });

        loadButton5.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        loadButton5.setText("Load");
        loadButton5.setMargin(new java.awt.Insets(2, 10, 2, 10));
        loadButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadButton5ActionPerformed(evt);
            }
        });

        savedGameLabel5.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        savedGameLabel5.setText("Player: Riccardo; Score: 300");

        clearButton5.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        clearButton5.setText("Clear");
        clearButton5.setMargin(new java.awt.Insets(2, 10, 2, 10));
        clearButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButton5ActionPerformed(evt);
            }
        });

        loadButton1.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        loadButton1.setText("Load");
        loadButton1.setMargin(new java.awt.Insets(2, 10, 2, 10));
        loadButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadButton1ActionPerformed(evt);
            }
        });

        clearButton1.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        clearButton1.setText("Clear");
        clearButton1.setMargin(new java.awt.Insets(2, 10, 2, 10));
        clearButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(savedGamesTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(savedGameLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(savedGameLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(savedGameLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(savedGameLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(loadButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(loadButton3))
                                .addComponent(loadButton4))
                            .addComponent(loadButton5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(clearButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(clearButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(clearButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(clearButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(savedGameLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(loadButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clearButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(savedGamesTitleLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(savedGameLabel1)
                    .addComponent(loadButton1)
                    .addComponent(clearButton1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(savedGameLabel2)
                    .addComponent(loadButton2)
                    .addComponent(clearButton2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(savedGameLabel3)
                    .addComponent(loadButton3)
                    .addComponent(clearButton3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(savedGameLabel4)
                    .addComponent(loadButton4)
                    .addComponent(clearButton4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(savedGameLabel5)
                    .addComponent(loadButton5)
                    .addComponent(clearButton5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

                                               

    private void clearButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                             
    	ControllerForView.getInstance().clearButtonPressed(1);
    }    
    
    private void clearButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                             
    	ControllerForView.getInstance().clearButtonPressed(2);
    }  
    
    private void clearButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                             
    	ControllerForView.getInstance().clearButtonPressed(3);
    }
    
    private void clearButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                             
    	ControllerForView.getInstance().clearButtonPressed(4);
    }
    
    private void clearButton5ActionPerformed(java.awt.event.ActionEvent evt) {                                             
    	ControllerForView.getInstance().clearButtonPressed(5);
    }  
    
    private void loadButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                            
    	ControllerForView.getInstance().loadSaveGameNumber(1);
    }
    
    private void loadButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                            
    	ControllerForView.getInstance().loadSaveGameNumber(2);
    }                                                                                    

    private void loadButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                            
    	ControllerForView.getInstance().loadSaveGameNumber(3);
    }                                           

    private void loadButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                            
    	ControllerForView.getInstance().loadSaveGameNumber(4);
    }                                           

    private void loadButton5ActionPerformed(java.awt.event.ActionEvent evt) {                                            
    	ControllerForView.getInstance().loadSaveGameNumber(5);
    }                                           

                                              

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SavedGamesWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SavedGamesWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SavedGamesWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SavedGamesWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SavedGamesWindow().setVisible(true);
            }
        });
    }
    
    public JLabel[] getLabels() {
    	JLabel[] lab = {savedGameLabel1, savedGameLabel2, savedGameLabel3, savedGameLabel4, savedGameLabel5};
    	return lab;
    }
    
    public static SavedGamesWindow getInstance() {
		if (instance == null) {
			instance = new SavedGamesWindow();
		}
		return instance;
	}

    // Variables declaration - do not modify                     
    private javax.swing.JButton clearButton1;
    private javax.swing.JButton clearButton2;
    private javax.swing.JButton clearButton3;
    private javax.swing.JButton clearButton4;
    private javax.swing.JButton clearButton5;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton loadButton1;
    private javax.swing.JButton loadButton2;
    private javax.swing.JButton loadButton3;
    private javax.swing.JButton loadButton4;
    private javax.swing.JButton loadButton5;
    private javax.swing.JLabel savedGameLabel1;
    private javax.swing.JLabel savedGameLabel2;
    private javax.swing.JLabel savedGameLabel3;
    private javax.swing.JLabel savedGameLabel4;
    private javax.swing.JLabel savedGameLabel5;
    private javax.swing.JLabel savedGamesTitleLabel;
    // End of variables declaration
}
