package jbreakout.view;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

import javax.swing.JButton;
import javax.swing.JLabel;

import jbreakout.controller.ControllerForView;
import jbreakout.util.Config;

public class ScoreBoardWindow extends javax.swing.JFrame {
	
	private static ScoreBoardWindow instance = null;
	

    /**
     * Creates new form ScoreBoardWindow
     */
    public ScoreBoardWindow() {
        initComponents();
        loadHiScores();
        addWindowListener(new WindowAdapter() {
        	public void windowClosing(WindowEvent evt) {
        		onExit();
    	    }
    	});
    }
    private void onExit() {
    	this.setVisible(false);
    	ControllerForView.getInstance().openStartWindow();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        highScoresLabel = new javax.swing.JLabel();
        labelScore1 = new javax.swing.JLabel();
        score1 = new javax.swing.JLabel();
        deleteButton1 = new javax.swing.JButton();
        deleteButton2 = new javax.swing.JButton();
        score2 = new javax.swing.JLabel();
        labelScore2 = new javax.swing.JLabel();
        labelScore3 = new javax.swing.JLabel();
        score3 = new javax.swing.JLabel();
        deleteButton3 = new javax.swing.JButton();
        deleteButton4 = new javax.swing.JButton();
        labelScore4 = new javax.swing.JLabel();
        score4 = new javax.swing.JLabel();
        deleteButton5 = new javax.swing.JButton();
        labelScore5 = new javax.swing.JLabel();
        score5 = new javax.swing.JLabel();
        deleteButton6 = new javax.swing.JButton();
        score6 = new javax.swing.JLabel();
        labelScore6 = new javax.swing.JLabel();
        labelScore7 = new javax.swing.JLabel();
        score7 = new javax.swing.JLabel();
        deleteButton7 = new javax.swing.JButton();
        labelScore8 = new javax.swing.JLabel();
        deleteButton8 = new javax.swing.JButton();
        score8 = new javax.swing.JLabel();
        closeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        highScoresLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        highScoresLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        highScoresLabel.setText("High Scores:");

        labelScore1.setText("Player 1");

        score1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        score1.setText("600");

        deleteButton1.setText("Delete");
        deleteButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButton1ActionPerformed(evt);
            }
        });

        deleteButton2.setText("Delete");
        deleteButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButton2ActionPerformed(evt);
            }
        });

        score2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        score2.setText("600");

        labelScore2.setText("Player 1");

        labelScore3.setText("Player 1");

        score3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        score3.setText("600");

        deleteButton3.setText("Delete");
        deleteButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButton3ActionPerformed(evt);
            }
        });

        deleteButton4.setText("Delete");
        deleteButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButton4ActionPerformed(evt);
            }
        });

        labelScore4.setText("Player 1");

        score4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        score4.setText("600");

        deleteButton5.setText("Delete");
        deleteButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButton5ActionPerformed(evt);
            }
        });

        labelScore5.setText("Player 1");

        score5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        score5.setText("600");

        deleteButton6.setText("Delete");
        deleteButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButton6ActionPerformed(evt);
            }
        });

        score6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        score6.setText("600");

        labelScore6.setText("Player 1");

        labelScore7.setText("Player 1");

        score7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        score7.setText("600");

        deleteButton7.setText("Delete");
        deleteButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButton7ActionPerformed(evt);
            }
        });

        labelScore8.setText("Player 1");

        deleteButton8.setText("Delete");
        deleteButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButton8ActionPerformed(evt);
            }
        });

        score8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        score8.setText("600");

        closeButton.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(highScoresLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelScore1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelScore2, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelScore6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelScore7, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelScore8, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelScore3, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelScore4, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelScore5, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(score1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(score2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(score3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(score4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(score5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(score6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(score7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(score8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(deleteButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(deleteButton2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(deleteButton3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(deleteButton4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(deleteButton5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(deleteButton6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(deleteButton7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(deleteButton8, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addComponent(closeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(184, 184, 184))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {labelScore1, labelScore2, labelScore3, labelScore4, labelScore5, labelScore6, labelScore7, labelScore8});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(highScoresLabel)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelScore1)
                    .addComponent(score1)
                    .addComponent(deleteButton1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelScore2)
                    .addComponent(score2)
                    .addComponent(deleteButton2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelScore3)
                    .addComponent(score3)
                    .addComponent(deleteButton3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelScore4)
                    .addComponent(score4)
                    .addComponent(deleteButton4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelScore5)
                    .addComponent(score5)
                    .addComponent(deleteButton5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelScore6)
                    .addComponent(score6)
                    .addComponent(deleteButton6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelScore7)
                    .addComponent(score7)
                    .addComponent(deleteButton7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelScore8)
                    .addComponent(score8)
                    .addComponent(deleteButton8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null); // Puts the window at the center of the screen.
    }// </editor-fold>                        

    private void deleteButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                              
        deleteButtonPressed(1);
    }                                             

    private void deleteButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                              
    	deleteButtonPressed(2);
    }                                             

    private void deleteButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                              
    	deleteButtonPressed(3);
   	}                                             

    private void deleteButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                              
    	deleteButtonPressed(4);
    }                                             

    private void deleteButton5ActionPerformed(java.awt.event.ActionEvent evt) {                                              
    	deleteButtonPressed(5);
    }                                             

    private void deleteButton6ActionPerformed(java.awt.event.ActionEvent evt) {                                              
    	deleteButtonPressed(6);
    }                                             

    private void deleteButton7ActionPerformed(java.awt.event.ActionEvent evt) {                                              
    	deleteButtonPressed(7);
    }                                             

    private void deleteButton8ActionPerformed(java.awt.event.ActionEvent evt) {                                              
    	deleteButtonPressed(8);
    }                                             

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {                                            
        onExit();
    }                                           

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScoreBoardWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScoreBoardWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScoreBoardWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScoreBoardWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScoreBoardWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton closeButton;
    private javax.swing.JButton deleteButton1;
    private javax.swing.JButton deleteButton2;
    private javax.swing.JButton deleteButton3;
    private javax.swing.JButton deleteButton4;
    private javax.swing.JButton deleteButton5;
    private javax.swing.JButton deleteButton6;
    private javax.swing.JButton deleteButton7;
    private javax.swing.JButton deleteButton8;
    private javax.swing.JLabel highScoresLabel;
    private javax.swing.JLabel labelScore1;
    private javax.swing.JLabel labelScore2;
    private javax.swing.JLabel labelScore3;
    private javax.swing.JLabel labelScore4;
    private javax.swing.JLabel labelScore5;
    private javax.swing.JLabel labelScore6;
    private javax.swing.JLabel labelScore7;
    private javax.swing.JLabel labelScore8;
    private javax.swing.JLabel score1;
    private javax.swing.JLabel score2;
    private javax.swing.JLabel score3;
    private javax.swing.JLabel score4;
    private javax.swing.JLabel score5;
    private javax.swing.JLabel score6;
    private javax.swing.JLabel score7;
    private javax.swing.JLabel score8;
    // End of variables declaration   
    
    private void loadHiScores() {
    	JLabel[] labArray = getNameLabels();
        JLabel[] scoreLabArray = getScoreLabels();
        for(int i = 0; i < labArray.length; i++) {
        	labArray[i].setText(Config.getInstance().getPlayerNameNumber(i + 1));
        	scoreLabArray[i].setText("" + Config.getInstance().getHighScoreNumber(i + 1));
        }
    }
    
    public void insertNewHighScore(int hiScore, String playername) {
		int lowI = lowestHiScoreIndex(hiScore);
		if(lowI <= 8) {
			Config.getInstance().setHighScoreNumber(lowI, hiScore);
	    	Config.getInstance().setPlayerNameNumber(lowI, playername);
	    	loadHiScores();
		}
    }
    
    public int actualHighScore() {
        JLabel[] scoreLabArray = getScoreLabels();
    	return Integer.parseInt(scoreLabArray[0].getText());
    }
    
    public int lowestScore() {
    	JLabel[] scoreLabArray = getScoreLabels();
    	return Integer.parseInt(scoreLabArray[scoreLabArray.length - 1].getText());
	}
    
    private int lowestHiScoreIndex(int min) {
    	int index;
    	JLabel[] scoreLabArray = getScoreLabels();
    	for(index = 0; index < scoreLabArray.length; index++) {
    		if(Integer.parseInt(scoreLabArray[index].getText()) <= min) {
    			break;
    		}
    	}
    	return index + 1;
    }
    
    private void deleteButtonPressed(int buttonNumber) {
    	JLabel[] labArray = getScoreLabels();
    	labArray[buttonNumber - 1].setText("0");
    	labArray = getNameLabels();
    	labArray[buttonNumber - 1].setText("Unknown");
    	
    	Config.getInstance().setHighScoreNumber(buttonNumber, 0);
    	Config.getInstance().setPlayerNameNumber(buttonNumber, "Unknown");
    }
    
    
    public JLabel[] getScoreLabels() {
    	JLabel[] scoreArray = {score1, score2, score3, score4, score5, score6, score7, score8};
    	return scoreArray;
    }
    
    public JLabel[] getNameLabels() {
    	JLabel[] scoreArray = {labelScore1, labelScore2, labelScore3, labelScore4, labelScore5, labelScore6, labelScore7, labelScore8};
    	return scoreArray;
    }
    
    public JButton[] getDeleteButtons() {
    	JButton[] scoreArray = {deleteButton1, deleteButton2, deleteButton3, deleteButton4, deleteButton5, deleteButton6, deleteButton7, deleteButton8};
    	return scoreArray;
    }
    
    public static ScoreBoardWindow getInstance() {
		if (instance == null) {
			instance = new ScoreBoardWindow();
		}
		return instance;
	}
}
